/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Message_new': RouteRecordInfo<
      'Message_new',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '404': RouteRecordInfo<
      '404',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    'Charts': RouteRecordInfo<
      'Charts',
      '/charts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Home': RouteRecordInfo<
      'Home',
      '/chatroom',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/chatSettings/': RouteRecordInfo<
      '/chatSettings/',
      '/chatSettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/codeLogin/': RouteRecordInfo<
      '/codeLogin/',
      '/codeLogin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Concat': RouteRecordInfo<
      'Concat',
      '/concat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Counter': RouteRecordInfo<
      'Counter',
      '/counter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Dialog': RouteRecordInfo<
      'Dialog',
      '/dialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/editProfile/': RouteRecordInfo<
      '/editProfile/',
      '/editProfile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ForgotPassword': RouteRecordInfo<
      'ForgotPassword',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fundDetails/': RouteRecordInfo<
      '/fundDetails/',
      '/fundDetails',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/generalSettings/': RouteRecordInfo<
      '/generalSettings/',
      '/generalSettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/generalSettings/aboutus': RouteRecordInfo<
      '/generalSettings/aboutus',
      '/generalSettings/aboutus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Main': RouteRecordInfo<
      'Main',
      '/index_old',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'KeepAlive': RouteRecordInfo<
      'KeepAlive',
      '/keepalive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Mock': RouteRecordInfo<
      'Mock',
      '/mock',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'My': RouteRecordInfo<
      'My',
      '/my',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/myProfile/': RouteRecordInfo<
      '/myProfile/',
      '/myProfile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nodata/': RouteRecordInfo<
      '/nodata/',
      '/nodata',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notificationSettings/': RouteRecordInfo<
      '/notificationSettings/',
      '/notificationSettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/payAdress/': RouteRecordInfo<
      '/payAdress/',
      '/payAdress',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/payAdress/searchTransacte': RouteRecordInfo<
      '/payAdress/searchTransacte',
      '/payAdress/searchTransacte',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/payAdress/transferRecord': RouteRecordInfo<
      '/payAdress/transferRecord',
      '/payAdress/transferRecord',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/paymentCollection/': RouteRecordInfo<
      '/paymentCollection/',
      '/paymentCollection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/payOrderId/': RouteRecordInfo<
      '/payOrderId/',
      '/payOrderId',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/payOrderId/searchTransacte': RouteRecordInfo<
      '/payOrderId/searchTransacte',
      '/payOrderId/searchTransacte',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/payOrderId/transferRecord': RouteRecordInfo<
      '/payOrderId/transferRecord',
      '/payOrderId/transferRecord',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/payPwd_new/editPayPwd': RouteRecordInfo<
      '/payPwd_new/editPayPwd',
      '/payPwd_new/editPayPwd',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/payPwd_new/forgetPayPwd': RouteRecordInfo<
      '/payPwd_new/forgetPayPwd',
      '/payPwd_new/forgetPayPwd',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/privacySettings/': RouteRecordInfo<
      '/privacySettings/',
      '/privacySettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Profile': RouteRecordInfo<
      'Profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/realNameAuth/': RouteRecordInfo<
      '/realNameAuth/',
      '/realNameAuth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/realnameAuth_new/': RouteRecordInfo<
      '/realnameAuth_new/',
      '/realnameAuth_new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/realnameAuth_new/advancedAuth': RouteRecordInfo<
      '/realnameAuth_new/advancedAuth',
      '/realnameAuth_new/advancedAuth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/realnameAuth_new/primaryAuth': RouteRecordInfo<
      '/realnameAuth_new/primaryAuth',
      '/realnameAuth_new/primaryAuth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reciptpaymethod_new/': RouteRecordInfo<
      '/reciptpaymethod_new/',
      '/reciptpaymethod_new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reciptpaymethod_new/alipay/': RouteRecordInfo<
      '/reciptpaymethod_new/alipay/',
      '/reciptpaymethod_new/alipay',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reciptpaymethod_new/alipay/add/': RouteRecordInfo<
      '/reciptpaymethod_new/alipay/add/',
      '/reciptpaymethod_new/alipay/add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reciptpaymethod_new/bank/': RouteRecordInfo<
      '/reciptpaymethod_new/bank/',
      '/reciptpaymethod_new/bank',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reciptpaymethod_new/bank/add/': RouteRecordInfo<
      '/reciptpaymethod_new/bank/add/',
      '/reciptpaymethod_new/bank/add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reciptpaymethod_new/wechat/': RouteRecordInfo<
      '/reciptpaymethod_new/wechat/',
      '/reciptpaymethod_new/wechat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reciptpaymethod_new/wechat/add/': RouteRecordInfo<
      '/reciptpaymethod_new/wechat/add/',
      '/reciptpaymethod_new/wechat/add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register/': RouteRecordInfo<
      '/register/',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/resetpwd/': RouteRecordInfo<
      '/resetpwd/',
      '/resetpwd',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ScrollCache': RouteRecordInfo<
      'ScrollCache',
      '/scroll-cache',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/securitySettings/': RouteRecordInfo<
      '/securitySettings/',
      '/securitySettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/securitySettings/changeEmail': RouteRecordInfo<
      '/securitySettings/changeEmail',
      '/securitySettings/changeEmail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/securitySettings/changePhone': RouteRecordInfo<
      '/securitySettings/changePhone',
      '/securitySettings/changePhone',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/securitySettings/changePhoneConfirm': RouteRecordInfo<
      '/securitySettings/changePhoneConfirm',
      '/securitySettings/changePhoneConfirm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/securitySettings/device': RouteRecordInfo<
      '/securitySettings/device',
      '/securitySettings/device',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Call_new': RouteRecordInfo<
      'Call_new',
      '/tabcall_new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Communicate_new': RouteRecordInfo<
      'Communicate_new',
      '/tabcommunicate_new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'My': RouteRecordInfo<
      'My',
      '/tabmy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'My_new': RouteRecordInfo<
      'My_new',
      '/tabmy_new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/taborder/': RouteRecordInfo<
      '/taborder/',
      '/taborder',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/taborder/detail/': RouteRecordInfo<
      '/taborder/detail/',
      '/taborder/detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/taborder/sellDetail/': RouteRecordInfo<
      '/taborder/sellDetail/',
      '/taborder/sellDetail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/taborder/sellDetail/successIndex': RouteRecordInfo<
      '/taborder/sellDetail/successIndex',
      '/taborder/sellDetail/successIndex',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Scan': RouteRecordInfo<
      'Scan',
      '/tabscan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tabtrade/': RouteRecordInfo<
      '/tabtrade/',
      '/tabtrade',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tabtrade/chooseBuyCoins': RouteRecordInfo<
      '/tabtrade/chooseBuyCoins',
      '/tabtrade/chooseBuyCoins',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/transferComp/': RouteRecordInfo<
      '/transferComp/',
      '/transferComp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/transferComp/searchTransacte': RouteRecordInfo<
      '/transferComp/searchTransacte',
      '/transferComp/searchTransacte',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/transferComp/transferRecord': RouteRecordInfo<
      '/transferComp/transferRecord',
      '/transferComp/transferRecord',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'UnoCSS': RouteRecordInfo<
      'UnoCSS',
      '/unocss',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'Message_new'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '404'
      views:
        | never
    }
    'src/pages/charts/index.vue': {
      routes:
        | 'Charts'
      views:
        | never
    }
    'src/pages/chatroom/index.vue': {
      routes:
        | 'Home'
      views:
        | never
    }
    'src/pages/chatSettings/index.vue': {
      routes:
        | '/chatSettings/'
      views:
        | never
    }
    'src/pages/codeLogin/index.vue': {
      routes:
        | '/codeLogin/'
      views:
        | never
    }
    'src/pages/concat/index.vue': {
      routes:
        | 'Concat'
      views:
        | never
    }
    'src/pages/counter/index.vue': {
      routes:
        | 'Counter'
      views:
        | never
    }
    'src/pages/dialog/index.vue': {
      routes:
        | 'Dialog'
      views:
        | never
    }
    'src/pages/editProfile/index.vue': {
      routes:
        | '/editProfile/'
      views:
        | never
    }
    'src/pages/forgot-password/index.vue': {
      routes:
        | 'ForgotPassword'
      views:
        | never
    }
    'src/pages/fundDetails/index.vue': {
      routes:
        | '/fundDetails/'
      views:
        | never
    }
    'src/pages/generalSettings/index.vue': {
      routes:
        | '/generalSettings/'
      views:
        | never
    }
    'src/pages/generalSettings/aboutus.vue': {
      routes:
        | '/generalSettings/aboutus'
      views:
        | never
    }
    'src/pages/index_old.vue': {
      routes:
        | 'Main'
      views:
        | never
    }
    'src/pages/keepalive/index.vue': {
      routes:
        | 'KeepAlive'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/pages/mock/index.vue': {
      routes:
        | 'Mock'
      views:
        | never
    }
    'src/pages/my/index.vue': {
      routes:
        | 'My'
      views:
        | never
    }
    'src/pages/myProfile/index.vue': {
      routes:
        | '/myProfile/'
      views:
        | never
    }
    'src/pages/nodata/index.vue': {
      routes:
        | '/nodata/'
      views:
        | never
    }
    'src/pages/notificationSettings/index.vue': {
      routes:
        | '/notificationSettings/'
      views:
        | never
    }
    'src/pages/payAdress/index.vue': {
      routes:
        | '/payAdress/'
      views:
        | never
    }
    'src/pages/payAdress/searchTransacte.vue': {
      routes:
        | '/payAdress/searchTransacte'
      views:
        | never
    }
    'src/pages/payAdress/transferRecord.vue': {
      routes:
        | '/payAdress/transferRecord'
      views:
        | never
    }
    'src/pages/paymentCollection/index.vue': {
      routes:
        | '/paymentCollection/'
      views:
        | never
    }
    'src/pages/payOrderId/index.vue': {
      routes:
        | '/payOrderId/'
      views:
        | never
    }
    'src/pages/payOrderId/searchTransacte.vue': {
      routes:
        | '/payOrderId/searchTransacte'
      views:
        | never
    }
    'src/pages/payOrderId/transferRecord.vue': {
      routes:
        | '/payOrderId/transferRecord'
      views:
        | never
    }
    'src/pages/payPwd_new/editPayPwd.vue': {
      routes:
        | '/payPwd_new/editPayPwd'
      views:
        | never
    }
    'src/pages/payPwd_new/forgetPayPwd.vue': {
      routes:
        | '/payPwd_new/forgetPayPwd'
      views:
        | never
    }
    'src/pages/privacySettings/index.vue': {
      routes:
        | '/privacySettings/'
      views:
        | never
    }
    'src/pages/profile/index.vue': {
      routes:
        | 'Profile'
      views:
        | never
    }
    'src/pages/realNameAuth/index.vue': {
      routes:
        | '/realNameAuth/'
      views:
        | never
    }
    'src/pages/realnameAuth_new/index.vue': {
      routes:
        | '/realnameAuth_new/'
      views:
        | never
    }
    'src/pages/realnameAuth_new/advancedAuth.vue': {
      routes:
        | '/realnameAuth_new/advancedAuth'
      views:
        | never
    }
    'src/pages/realnameAuth_new/primaryAuth.vue': {
      routes:
        | '/realnameAuth_new/primaryAuth'
      views:
        | never
    }
    'src/pages/reciptpaymethod_new/index.vue': {
      routes:
        | '/reciptpaymethod_new/'
      views:
        | never
    }
    'src/pages/reciptpaymethod_new/alipay/index.vue': {
      routes:
        | '/reciptpaymethod_new/alipay/'
      views:
        | never
    }
    'src/pages/reciptpaymethod_new/alipay/add/index.vue': {
      routes:
        | '/reciptpaymethod_new/alipay/add/'
      views:
        | never
    }
    'src/pages/reciptpaymethod_new/bank/index.vue': {
      routes:
        | '/reciptpaymethod_new/bank/'
      views:
        | never
    }
    'src/pages/reciptpaymethod_new/bank/add/index.vue': {
      routes:
        | '/reciptpaymethod_new/bank/add/'
      views:
        | never
    }
    'src/pages/reciptpaymethod_new/wechat/index.vue': {
      routes:
        | '/reciptpaymethod_new/wechat/'
      views:
        | never
    }
    'src/pages/reciptpaymethod_new/wechat/add/index.vue': {
      routes:
        | '/reciptpaymethod_new/wechat/add/'
      views:
        | never
    }
    'src/pages/register/index.vue': {
      routes:
        | '/register/'
      views:
        | never
    }
    'src/pages/resetpwd/index.vue': {
      routes:
        | '/resetpwd/'
      views:
        | never
    }
    'src/pages/scroll-cache/index.vue': {
      routes:
        | 'ScrollCache'
      views:
        | never
    }
    'src/pages/securitySettings/index.vue': {
      routes:
        | '/securitySettings/'
      views:
        | never
    }
    'src/pages/securitySettings/changeEmail.vue': {
      routes:
        | '/securitySettings/changeEmail'
      views:
        | never
    }
    'src/pages/securitySettings/changePhone.vue': {
      routes:
        | '/securitySettings/changePhone'
      views:
        | never
    }
    'src/pages/securitySettings/changePhoneConfirm.vue': {
      routes:
        | '/securitySettings/changePhoneConfirm'
      views:
        | never
    }
    'src/pages/securitySettings/device.vue': {
      routes:
        | '/securitySettings/device'
      views:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
    }
    'src/pages/tabcall_new/index.vue': {
      routes:
        | 'Call_new'
      views:
        | never
    }
    'src/pages/tabcommunicate_new/index.vue': {
      routes:
        | 'Communicate_new'
      views:
        | never
    }
    'src/pages/tabmy/index.vue': {
      routes:
        | 'My'
      views:
        | never
    }
    'src/pages/tabmy_new/index.vue': {
      routes:
        | 'My_new'
      views:
        | never
    }
    'src/pages/taborder/index.vue': {
      routes:
        | '/taborder/'
      views:
        | never
    }
    'src/pages/taborder/detail/index.vue': {
      routes:
        | '/taborder/detail/'
      views:
        | never
    }
    'src/pages/taborder/sellDetail/index.vue': {
      routes:
        | '/taborder/sellDetail/'
      views:
        | never
    }
    'src/pages/taborder/sellDetail/successIndex.vue': {
      routes:
        | '/taborder/sellDetail/successIndex'
      views:
        | never
    }
    'src/pages/tabscan/index.vue': {
      routes:
        | 'Scan'
      views:
        | never
    }
    'src/pages/tabtrade/index.vue': {
      routes:
        | '/tabtrade/'
      views:
        | never
    }
    'src/pages/tabtrade/chooseBuyCoins.vue': {
      routes:
        | '/tabtrade/chooseBuyCoins'
      views:
        | never
    }
    'src/pages/transferComp/index.vue': {
      routes:
        | '/transferComp/'
      views:
        | never
    }
    'src/pages/transferComp/searchTransacte.vue': {
      routes:
        | '/transferComp/searchTransacte'
      views:
        | never
    }
    'src/pages/transferComp/transferRecord.vue': {
      routes:
        | '/transferComp/transferRecord'
      views:
        | never
    }
    'src/pages/unocss/index.vue': {
      routes:
        | 'UnoCSS'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
